# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(434, 512)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.Carregar = QtWidgets.QPushButton(self.centralWidget)
        self.Carregar.setGeometry(QtCore.QRect(90, 30, 75, 23))
        self.Carregar.setObjectName("Carregar")
        self.ImagemOri = QtWidgets.QLabel(self.centralWidget)
        self.ImagemOri.setGeometry(QtCore.QRect(50, 70, 321, 271))
        self.ImagemOri.setText("")
        self.ImagemOri.setObjectName("ImagemOri")
        self.Salvar = QtWidgets.QPushButton(self.centralWidget)
        self.Salvar.setGeometry(QtCore.QRect(260, 30, 75, 23))
        self.Salvar.setObjectName("Salvar")
        self.X1 = QtWidgets.QLineEdit(self.centralWidget)
        self.X1.setGeometry(QtCore.QRect(110, 370, 31, 31))
        self.X1.setObjectName("X1")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(70, 380, 46, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(220, 380, 46, 13))
        self.label_4.setObjectName("label_4")
        self.X2 = QtWidgets.QLineEdit(self.centralWidget)
        self.X2.setGeometry(QtCore.QRect(160, 370, 31, 31))
        self.X2.setObjectName("X2")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(140, 370, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.Y1 = QtWidgets.QLineEdit(self.centralWidget)
        self.Y1.setGeometry(QtCore.QRect(260, 370, 31, 31))
        self.Y1.setObjectName("Y1")
        self.Y2 = QtWidgets.QLineEdit(self.centralWidget)
        self.Y2.setGeometry(QtCore.QRect(310, 370, 31, 31))
        self.Y2.setObjectName("Y2")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(290, 370, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(120, 430, 46, 13))
        self.label_7.setObjectName("label_7")
        self.C1 = QtWidgets.QLineEdit(self.centralWidget)
        self.C1.setGeometry(QtCore.QRect(170, 420, 31, 31))
        self.C1.setObjectName("C1")
        self.C2 = QtWidgets.QLineEdit(self.centralWidget)
        self.C2.setGeometry(QtCore.QRect(220, 420, 31, 31))
        self.C2.setObjectName("C2")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(200, 420, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(250, 420, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.C3 = QtWidgets.QLineEdit(self.centralWidget)
        self.C3.setGeometry(QtCore.QRect(270, 420, 31, 31))
        self.C3.setObjectName("C3")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 434, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Carregar.setText(_translate("MainWindow", "Carregar"))
        self.Salvar.setText(_translate("MainWindow", "Salvar"))
        self.X1.setText(_translate("MainWindow", "70"))
        self.label_3.setText(_translate("MainWindow", "Pixel X"))
        self.label_4.setText(_translate("MainWindow", "Pixel Y"))
        self.X2.setText(_translate("MainWindow", "100"))
        self.label_5.setText(_translate("MainWindow", " :"))
        self.Y1.setText(_translate("MainWindow", "70"))
        self.Y2.setText(_translate("MainWindow", "100"))
        self.label_6.setText(_translate("MainWindow", " :"))
        self.label_7.setText(_translate("MainWindow", "NewColor"))
        self.C1.setText(_translate("MainWindow", "0"))
        self.C2.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", " :"))
        self.label_9.setText(_translate("MainWindow", " :"))
        self.C3.setText(_translate("MainWindow", "255"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

